spring:
  application:
    name: cozastore03
  config:
    import: optional:classpath:application-local.yaml
  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    username: root
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# server:
#   port: 8080
# logging:
#   level:
#     root: INFO
#     org.springframework.security: INFO
